apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testing
spec:
  generators:
  - git:
      repoURL: https://github.com/acolominas/helm-chart-testing.git
      revision: HEAD
      directories:
        - path: "values/*"
  template:
    metadata:
      name: '{{path.basename}}-testing'
      namespace: argocd
    spec:
      project: testing
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://github.com/acolominas/helm-chart-testing.git
        targetRevision: 0.1.0
        path: "test"
        helm:
          valueFiles:
            - values.yaml
            - ../values/{{path.basename}}/values.yaml
      destination:
        name: in-cluster
        namespace: '{{path.basename}}'
